(defun color-theme-lijsf2 ()
  (interactive)
  (color-theme-install
   '(color-theme-lijsf2
      ((background-color . "#272f34")
      (background-mode . light)
      (border-color . "#232323")
      (cursor-color . "#abb2c4")
      (foreground-color . "#8e8780")
      (mouse-color . "black"))
     (fringe ((t (:background "#232323"))))
     (mode-line ((t (:foreground "#ffffff" :background "#323232"))))
     (region ((t (:background "#555577"))))
     (font-lock-builtin-face ((t (:foreground "#d0d0ff"))))
     (font-lock-comment-face ((t (:foreground "#bc9458"))))
     (font-lock-function-name-face ((t (:foreground "#ffc66d"))))
     (font-lock-keyword-face ((t (:foreground "#cc7833"))))
     (font-lock-string-face ((t (:foreground "#a5c261"))))
     (font-lock-type-face ((t (:foreground"#ffffff"))))
     (font-lock-constant-face ((t (:foreground "#6d9cbe"))))
     (font-lock-variable-name-face ((t (:foreground "#afc3dd"))))
     (minibuffer-prompt ((t (:foreground "#ffffff" :bold t))))
     (font-lock-warning-face ((t (:foreground "red" :bold t))))
     )))
(provide 'color-theme-lijsf2)
